#!/bin/bash

# First get the config .plist set up.
if [ -f /Library/Managed\ Installs/initial-config/ManagedInstalls.plist ]; then
    GOODONE=`defaults read /Library/Managed\ Installs/initial-config/ManagedInstalls.plist SuccessfulInstall`
    if [ "$GOODONE" = "1" ]; then
        defaults delete /Library/Managed\ Installs/initial-config/ManagedInstalls.plist SuccessfulInstall
        defaults delete /Library/Preferences/ManagedInstalls.plist
        defaults import /Library/Preferences/ManagedInstalls.plist /Library/Managed\ Installs/initial-config/ManagedInstalls.plist
        rm -f /Library/Managed\ Installs/initial-config/ManagedInstalls.plist
    fi
fi    

# Second, get the reconfigure piece working.  Figure out what's installed.
if [ -d /usr/local/munki/preflight.d ]; then
    if [ ! -f /usr/local/munki/preflight.d/00_MTM.reconfigure ]; then
        cp /usr/local/munki/00_MTM.reconfigure /usr/local/munki/preflight.d
    fi
else
    mkdir /usr/local/munki/preflight.d
    cp /usr/local/munki/00_MTM.reconfigure /usr/local/munki/preflight.d
    if [ -x /usr/local/munki/preflight ]; then
        mv /usr/local/munki/preflight /usr/local/munki/preflight.d/01_historic_preflight
    fi
    ln -s /usr/local/munki/00_MTM.run_directory /usr/local/munki/preflight
fi

killall "Managed Software Center"

