#!/bin/bash

PREFLIGHTD=/usr/local/munki/preflight.d
PREABORTD=/usr/local/munki/preflight_abort.d

# First get the config .plist set up.
if [ -f /Library/Managed\ Installs/initial-config/ManagedInstalls.plist ]; then
    GOODONE=`defaults read /Library/Managed\ Installs/initial-config/ManagedInstalls.plist SuccessfulInstall`
    if [ "$GOODONE" = "1" ]; then
        defaults delete /Library/Managed\ Installs/initial-config/ManagedInstalls.plist SuccessfulInstall
        defaults delete /Library/Preferences/ManagedInstalls.plist
        defaults import /Library/Preferences/ManagedInstalls.plist /Library/Managed\ Installs/initial-config/ManagedInstalls.plist
        rm -f /Library/Managed\ Installs/initial-config/ManagedInstalls.plist
    fi
fi    

# Second, get the reconfigure piece working.  Figure out what's installed.
if [ -d $PREFLIGHTD ]; then
    if [ ! -f $PREFLIGHTD/00_MTM.reconfigure.sh ]; then
        cp /usr/local/munki/00_MTM.reconfigure.sh $PREFLIGHTD
    fi
    if [ -f $PREFLIGHTD/00_MTM.reconfigure ]; then
        rm $PREFLIGHTD/00_MTM.reconfigure
    fi
else
    mkdir $PREFLIGHTD
    cp /usr/local/munki/00_MTM.reconfigure.sh $PREFLIGHTD
    if [ -x /usr/local/munki/preflight ]; then
        mv /usr/local/munki/preflight $PREFLIGHTD/01_historic_preflight
    fi
    #ln -s /usr/local/munki/00_MTM.run_directory /usr/local/munki/preflight
fi

# Create the preflight symlink
ln -sfn /usr/local/munki/00_MTM.run_directory /usr/local/munki/preflight

# Second, get the reconfigure piece working.  Figure out what's installed.
if [ ! -d $PREABORTD ]; then
    mkdir $PREABORTD
fi

killall "Managed Software Center"

